import React, { useState, useEffect } from 'react';
import {
   Scale, Calculator, ArrowRight,
   MessageSquare, ArrowLeft,
   Sparkles, Zap, GraduationCap, ShieldCheck, User, Plus, Star, MapPin, Globe, Calendar, Terminal, Briefcase, Map
} from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { GoogleGenAI } from "@google/genai";
import { institutions } from '../data/mockData';

// const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const Tools = () => {
   const [searchParams, setSearchParams] = useSearchParams();
   const activeTool = searchParams.get('tool');

   useEffect(() => {
      window.scrollTo(0, 0);
   }, [activeTool]);

   const handleBack = () => {
      setSearchParams({});
      window.scrollTo(0, 0);
   };

   const tools = [
      {
         title: "Z-Score Analysis",
         desc: "Simulate your university admission probability based on GCE A/L performance metrics.",
         image: "https://images.unsplash.com/photo-1543286386-2e659306cd6c?q=80&w=800",
         action: "z-score",
         badge: "UGC Model"
      },
      {
         title: "AI Career Advisor",
         desc: "Get a personalized academic and professional roadmap generated by Gemini AI.",
         image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800",
         action: "career",
         badge: "AI Powered"
      },
      {
         title: "Comparison Matrix",
         desc: "Analyze up to three educational institutions side-by-side using key performance data.",
         image: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=800",
         action: "compare"
      },
      {
         title: "Admission Sync",
         desc: "Live tracking of application intake windows for major local and private universities.",
         image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=800",
         action: "deadlines"
      }
   ];

   if (activeTool === 'z-score') return <ZScoreView onBack={handleBack} />;
   if (activeTool === 'career') return <CareerView onBack={handleBack} />;
   if (activeTool === 'compare') return <CompareView onBack={handleBack} />;
   if (activeTool === 'deadlines') return <DeadlinesView onBack={handleBack} />;

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 pb-24">
         {/* HEADER SECTION */}
         <div className="bg-slate-950 py-32 md:py-48 mb-16 relative overflow-hidden flex items-center justify-center">
            <div className="absolute inset-0 opacity-10">
               <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-blue-600 rounded-full blur-[200px] translate-x-1/2 -translate-y-1/2"></div>
            </div>
            <div className="container mx-auto px-6 text-center relative z-10 animate-fade-in-up">
               <span className="text-primary-500 font-bold uppercase tracking-[0.4em] text-[10px] mb-6 block">STRATEGIC PLANNING SUITE</span>
               <h1 className="text-6xl md:text-8xl font-black text-white mb-8 tracking-tighter">Academic Hub.</h1>
               <p className="text-slate-400 text-lg md:text-xl max-w-2xl mx-auto font-medium leading-relaxed">
                  Data-driven modules designed to provide clarity and precision during your higher education journey.
               </p>
            </div>
         </div>

         <div className="container mx-auto px-6 -mt-24">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
               {tools.map((tool, i) => (
                  <div key={i} onClick={() => setSearchParams({ tool: tool.action })} className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 hover:border-primary-500 hover:shadow-premium transition-all duration-500 cursor-pointer group flex flex-col md:flex-row overflow-hidden reveal">
                     <div className="md:w-1/3 h-64 md:h-auto overflow-hidden relative">
                        <img src={tool.image} alt={tool.title} className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" />
                        <div className="absolute inset-0 bg-gradient-to-t md:bg-gradient-to-r from-slate-950/60 to-transparent"></div>
                        {tool.badge && <span className="absolute top-6 left-6 bg-primary-600 text-white text-[9px] font-black px-4 py-2 rounded-xl uppercase tracking-widest">{tool.badge}</span>}
                     </div>
                     <div className="p-10 md:w-2/3 flex flex-col justify-center">
                        <h3 className="text-3xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">{tool.title}</h3>
                        <p className="text-slate-500 dark:text-slate-400 text-base mb-10 leading-relaxed font-medium">{tool.desc}</p>
                        <div className="flex items-center text-primary-600 font-black uppercase tracking-[0.2em] text-[10px] group-hover:translate-x-2 transition-all">
                           Open Module <ArrowRight size={18} className="ml-3" />
                        </div>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </div>
   );
};

const CareerView = ({ onBack }: { onBack: () => void }) => {
   const [interest, setInterest] = useState('');
   const [loading, setLoading] = useState(false);
   const [roadmap, setRoadmap] = useState<{ step: string, desc: string }[]>([]);

   const generateRoadmap = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!interest.trim()) return;
      setLoading(true);
      try {
         // const response = await ai.models.generateContent({
         //   model: 'gemini-3-flash-preview',
         //   contents: `Generate a 4-step academic and professional roadmap for someone interested in: ${interest}. Context: Sri Lanka.`,
         //   config: {
         //     responseMimeType: "application/json",
         //     responseSchema: {
         //       type: "ARRAY",
         //       items: {
         //         type: "OBJECT",
         //         properties: {
         //           step: { type: "STRING" },
         //           desc: { type: "STRING" }
         //         },
         //         required: ["step", "desc"]
         //       }
         //     }
         //   }
         // });
         // const data = JSON.parse(response.text || '[]');
         // setRoadmap(data);
      } catch (err) {
         console.error(err);
         setRoadmap([{ step: "Consultancy Error", desc: "Unable to reach AI advisor." }]);
      } finally {
         setLoading(false);
      }
   };

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-4xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="grid grid-cols-1 gap-12">
               <div className="bg-white dark:bg-slate-900 rounded-[3rem] p-12 border border-slate-100 dark:border-slate-800 shadow-premium reveal">
                  <div className="flex items-center gap-6 mb-12">
                     <div className="w-16 h-16 bg-primary-600 text-white rounded-[1.5rem] flex items-center justify-center shadow-premium"><Briefcase size={32} /></div>
                     <div>
                        <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight uppercase">AI Path Advisor</h2>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Intelligent Career Roadmap Generator</p>
                     </div>
                  </div>
                  <form onSubmit={generateRoadmap} className="space-y-10">
                     <div>
                        <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-4 ml-1">What are you passionate about?</label>
                        <textarea required value={interest} onChange={e => setInterest(e.target.value)} placeholder="e.g. Software engineering, marine biology, investment banking..." className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-8 py-6 font-bold outline-none focus:ring-4 focus:ring-primary-500/10 transition-all h-32 resize-none text-slate-900 dark:text-white" />
                     </div>
                     <button type="submit" disabled={loading} className="w-full bg-primary-600 text-white font-bold uppercase tracking-[0.3em] text-[11px] py-6 rounded-2xl transition-all shadow-premium hover:bg-primary-700 active:scale-95 disabled:opacity-40">
                        {loading ? 'Consulting Gemini Intelligence...' : 'Generate Roadmap'}
                     </button>
                  </form>
               </div>

               {roadmap.length > 0 && (
                  <div className="space-y-6 animate-fade-in-up">
                     <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] mb-8 text-center">Your Strategic Roadmap</h3>
                     {roadmap.map((item, i) => (
                        <div key={i} className="flex gap-8 group">
                           <div className="flex flex-col items-center">
                              <div className="w-10 h-10 bg-primary-600 text-white rounded-xl flex items-center justify-center font-bold text-sm shadow-premium z-10 shrink-0">{i + 1}</div>
                              {i < roadmap.length - 1 && <div className="w-0.5 h-full bg-slate-100 dark:bg-slate-800 my-2"></div>}
                           </div>
                           <div className="pb-12 pt-1">
                              <h4 className="text-xl font-black text-slate-900 dark:text-white mb-2 uppercase tracking-tight">{item.step}</h4>
                              <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">{item.desc}</p>
                           </div>
                        </div>
                     ))}
                  </div>
               )}
            </div>
         </div>
      </div>
   );
};

// ... keep existing ZScoreView, CompareView, DeadlinesView implementations ...
const ZScoreView = ({ onBack }: { onBack: () => void }) => {
   const [stream, setStream] = useState('');
   const [district, setDistrict] = useState('');
   const [subjectSelections, setSubjectSelections] = useState<any[]>([]);
   const [loading, setLoading] = useState(false);
   const [result, setResult] = useState<any>(null);

   const streamsList = ['Physical Science', 'Bio Science', 'Commerce', 'Technology', 'Arts'];
   const districts = ["Colombo", "Gampaha", "Kandy", "Galle", "Kalutara", "Kurunegala", "Matara", "Badulla", "Anuradhapura"];

   useEffect(() => {
      if (!stream) return setSubjectSelections([]);
      const config: any = {
         'Physical Science': ['Combined Maths', 'Physics', 'Chemistry'],
         'Bio Science': ['Biology', 'Chemistry', 'Physics'],
         'Commerce': ['Economics', 'Business Studies', 'Accounting']
      };
      setSubjectSelections((config[stream] || ['Subject 1', 'Subject 2', 'Subject 3']).map((s: string) => ({ name: s, grade: '' })));
   }, [stream]);

   const calculate = (e: any) => {
      e.preventDefault();
      setLoading(true);
      setTimeout(() => {
         setResult({ score: (Math.random() * 1.8 + 0.8).toFixed(4), status: "Admission Highly Likely" });
         setLoading(false);
      }, 1500);
   };

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-5xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
               <div className="bg-white dark:bg-slate-900 rounded-[3rem] p-12 border border-slate-100 dark:border-slate-800 shadow-premium reveal">
                  <div className="flex items-center gap-6 mb-12">
                     <div className="w-16 h-16 bg-primary-600 text-white rounded-[1.5rem] flex items-center justify-center shadow-premium"><Calculator size={32} /></div>
                     <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight uppercase">Z-Score Tool</h2>
                  </div>
                  <form onSubmit={calculate} className="space-y-8">
                     <div className="grid grid-cols-2 gap-4">
                        <select className="bg-slate-50 dark:bg-slate-800 rounded-xl px-6 py-4 font-bold outline-none" value={district} onChange={e => setDistrict(e.target.value)}>
                           <option value="">District</option>
                           {districts.map(d => <option key={d}>{d}</option>)}
                        </select>
                        <select className="bg-slate-50 dark:bg-slate-800 rounded-xl px-6 py-4 font-bold outline-none" value={stream} onChange={e => setStream(e.target.value)}>
                           <option value="">Stream</option>
                           {streamsList.map(s => <option key={s}>{s}</option>)}
                        </select>
                     </div>
                     {subjectSelections.map((s, i) => (
                        <div key={i} className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/30 rounded-2xl border border-slate-100 dark:border-slate-800">
                           <span className="text-sm font-bold text-slate-800 dark:text-slate-200">{s.name}</span>
                           <select className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-2 font-black text-xs" value={s.grade} onChange={(e) => { const updated = [...subjectSelections]; updated[i].grade = e.target.value; setSubjectSelections(updated); }}><option value="">Grade</option><option>A</option><option>B</option><option>C</option><option>S</option><option>F</option></select>
                        </div>
                     ))}
                     <button type="submit" disabled={!stream || loading} className="w-full bg-slate-900 dark:bg-primary-600 text-white font-bold uppercase tracking-[0.2em] text-[10px] py-6 rounded-2xl transition-all shadow-premium">
                        {loading ? 'Running UGC Model...' : 'Calculate Prediction'}
                     </button>
                  </form>
               </div>
               <div className="flex flex-col justify-center">
                  {result ? (
                     <div className="bg-slate-900 rounded-[3.5rem] p-16 text-center animate-fade-in-up">
                        <h3 className="text-[10px] font-bold text-slate-500 uppercase tracking-[0.4em] mb-6">Estimated Score</h3>
                        <div className="text-8xl font-black text-white mb-10 tracking-tighter">{result.score}</div>
                        <div className="inline-flex items-center gap-3 bg-emerald-500/10 text-emerald-500 text-[10px] font-bold uppercase tracking-[0.2em] px-8 py-4 rounded-2xl border border-emerald-500/20">
                           <ShieldCheck size={20} /> {result.status}
                        </div>
                     </div>
                  ) : (
                     <div className="h-full min-h-[400px] border-4 border-dashed border-slate-100 dark:border-slate-800 rounded-[3.5rem] flex flex-col items-center justify-center text-center p-12">
                        <Terminal size={48} className="text-slate-100 dark:text-slate-800 mb-6" />
                        <p className="text-slate-300 font-bold uppercase tracking-widest text-xs">Ready for Calculation</p>
                     </div>
                  )}
               </div>
            </div>
         </div>
      </div>
   );
};

const CompareView = ({ onBack }: { onBack: () => void }) => {
   const [selected, setSelected] = useState<string[]>([]);
   const selectedInsts = institutions.filter(i => selected.includes(i.id));

   const toggleSelection = (id: string) => {
      if (selected.includes(id)) {
         setSelected(selected.filter(s => s !== id));
      } else if (selected.length < 3) {
         setSelected([...selected, id]);
      }
   };

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-7xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Matrix</button>
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
               <div className="lg:col-span-1 bg-white dark:bg-slate-900 p-8 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-premium">
                  <h3 className="font-black mb-8 text-[10px] uppercase tracking-widest text-slate-400">Select Target (Max 3)</h3>
                  <div className="space-y-2">
                     {institutions.map(inst => (
                        <button
                           key={inst.id}
                           onClick={() => toggleSelection(inst.id)}
                           className={`w-full text-left px-5 py-4 rounded-2xl border transition-all text-sm font-bold ${selected.includes(inst.id) ? 'border-primary-500 bg-primary-50 text-primary-600' : 'border-slate-50 dark:border-slate-800 hover:border-slate-200 text-slate-600 dark:text-slate-400'}`}
                        >
                           {inst.name}
                        </button>
                     ))}
                  </div>
               </div>
               <div className="lg:col-span-3">
                  {selected.length === 0 ? (
                     <div className="h-full border-4 border-dashed border-slate-100 dark:border-slate-800 rounded-[3rem] flex flex-col items-center justify-center p-20 text-center">
                        <Scale size={48} className="mb-6 text-slate-100 dark:text-slate-800" />
                        <h3 className="text-xl font-bold uppercase tracking-tight text-slate-300">Comparison Engine Idle</h3>
                     </div>
                  ) : (
                     <div className="bg-white dark:bg-slate-900 rounded-[3rem] border border-slate-100 dark:border-slate-800 overflow-hidden shadow-premium">
                        <div className="grid grid-cols-[200px_repeat(auto-fit,minmax(150px,1fr))] divide-x divide-slate-100 dark:divide-slate-800">
                           <div className="p-8 bg-slate-50 dark:bg-slate-950 font-black text-[9px] text-slate-400 uppercase tracking-widest flex items-center">Institution Metrics</div>
                           {selectedInsts.map(inst => (
                              <div key={inst.id} className="p-8 text-center bg-slate-50 dark:bg-slate-950">
                                 <div className="font-black text-xs text-slate-900 dark:text-white uppercase leading-tight">{inst.name}</div>
                              </div>
                           ))}
                           <div className="p-8 text-[9px] font-bold text-slate-500 uppercase tracking-widest border-t border-slate-100 dark:border-slate-800">Classification</div>
                           {selectedInsts.map(inst => (
                              <div key={inst.id} className="p-8 text-center border-t border-slate-100 dark:border-slate-800 font-bold text-xs">{inst.type}</div>
                           ))}
                           <div className="p-8 text-[9px] font-bold text-slate-500 uppercase tracking-widest border-t border-slate-100 dark:border-slate-800">Rating</div>
                           {selectedInsts.map(inst => (
                              <div key={inst.id} className="p-8 text-center border-t border-slate-100 dark:border-slate-800 font-black text-primary-600 text-xl">{inst.rating}</div>
                           ))}
                        </div>
                     </div>
                  )}
               </div>
            </div>
         </div>
      </div>
   );
};

const DeadlinesView = ({ onBack }: { onBack: () => void }) => {
   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-4xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="flex items-center gap-6 mb-16 animate-fade-in-up">
               <div className="w-16 h-16 bg-primary-600 text-white rounded-2xl flex items-center justify-center shadow-premium"><Calendar size={32} /></div>
               <div>
                  <h1 className="text-4xl font-black text-slate-900 dark:text-white uppercase tracking-tight">Intake Sync</h1>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Application Cycle Tracker</p>
               </div>
            </div>
            <div className="space-y-4">
               {[
                  { title: "UGC State University Intake", date: "Oct 15, 2024", tag: "Government", urgent: true },
                  { title: "SLIIT Semester One Admissions", date: "Sep 30, 2024", tag: "Private", urgent: true },
                  { title: "VTA Vocational Enrollment", date: "Dec 12, 2024", tag: "Vocational", urgent: false }
               ].map((item, i) => (
                  <div key={i} className="bg-white dark:bg-slate-900 p-10 rounded-4xl border border-slate-100 dark:border-slate-800 flex justify-between items-center group hover:shadow-premium transition-all">
                     <div>
                        <span className="text-[9px] font-bold text-primary-600 uppercase tracking-widest bg-primary-50 px-4 py-1.5 rounded-lg mb-4 inline-block">{item.tag}</span>
                        <h3 className="font-black text-2xl text-slate-900 dark:text-white group-hover:text-primary-600 transition-colors">{item.title}</h3>
                     </div>
                     <div className="text-right">
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Final Deadline</p>
                        <p className={`text-xl font-black ${item.urgent ? 'text-red-500' : 'text-slate-900 dark:text-white'}`}>{item.date}</p>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </div>
   );
};

const ForumView = ({ onBack }: { onBack: () => void }) => null; // Placeholder for logic balance

export default Tools;