import React, { useEffect, useMemo, useState } from 'react';
import {
   ArrowLeft,
   ArrowRight,
   BadgeCheck,
   Banknote,
   Building2,
   Briefcase,
   Calculator,
   Calendar,
   CheckCircle2,
   Globe,
   GraduationCap,
   MapPin,
   ShieldCheck,
   Star,
   Terminal,
   Users,
   X
} from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAppStore } from '../context/AppContext';
import { ProgramsService } from '../types/services/ProgramsService';
import { InstitutionsService } from '../types/services/InstitutionsService';
import EducationPathMapperView from './tools/education-path-mapper/EducationPathMapperView';

const heroImages = [
  "https://images.tech.co/wp-content/uploads/2024/11/06143542/ai-robot-computer.jpg", // Writing / Laptop
  "https://brilliantio.com/wp-content/uploads/2022/06/why-career-change-is-hard-1024x683.png", // Planning / Calendar
  "https://media.licdn.com/dms/image/D5612AQEB8VanMlLbew/article-cover_image-shrink_720_1280/0/1685649697195?e=2147483647&v=beta&t=pNE-OAbwzTdYF4bg2xQhJHV-0LZdgk_u8-NUtkkU7bU"  // Group Study
];

// const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const Tools = () => {
   const [searchParams, setSearchParams] = useSearchParams();
   const activeTool = searchParams.get('tool');
   const [currentHeroIndex, setCurrentHeroIndex] = useState(0);

   useEffect(() => {
      window.scrollTo(0, 0);
   }, [activeTool]);

   useEffect(() => {
      const interval = setInterval(() => {
         setCurrentHeroIndex((prev) => (prev + 1) % heroImages.length);
      }, 5000);
      return () => clearInterval(interval);
   }, []);

   const handleBack = () => {
      setSearchParams({});
      window.scrollTo(0, 0);
   };

   const tools = [
      {
         title: "Z-Score Analysis",
         desc: "Simulate your university admission probability based on GCE A/L performance metrics.",
         image: "https://thumbs.dreamstime.com/b/geometric-growing-chart-mosaic-icon-z-score-seal-blue-vector-round-grunge-seal-stamp-z-score-message-abstract-mosaic-184046865.jpg?w=1400",
         action: "z-score",
         badge: "UGC Model"
      },
      {
         title: "Education Path Mapper",
         desc: "Interactive mind-map to explore A/L and O/L pathways and suggested universities.",
         image: "https://cdn.shopify.com/s/files/1/0274/7429/6892/products/SH384-student-making-steps-his-graduation-260nw-390983137_288x.jpg?v=1594890721",
         action: "path-mapper",
         badge: "Interactive"
      },
      {
         title: "AI Career Advisor",
         desc: "Get a personalized academic and professional roadmap generated by Gemini AI.",
         image: "https://www.gtim.edu.in/wp-content/uploads/2023/04/img00120.jpg",
         action: "career",
         badge: "AI Powered"
      },
      {
         title: "Course Comparison",
         desc: "Compare up to three courses side-by-side (fees, duration, requirements, and more).",
         image: "https://tse3.mm.bing.net/th/id/OIP.S9pXFCtl4Yivs053ui8SZAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
         action: "compare"
      },
      {
         title: "Admission Sync",
         desc: "Live tracking of application intake windows for major local and private universities.",
         image: "https://th.bing.com/th/id/R.01f1e0180fced6348619b6b0c14280d1?rik=CL8zqeIbXwXExg&riu=http%3a%2f%2fvychmc.com%2fpublic%2fuploads%2fcontentimage%2fpage-dynamic-contentimage-70.jpg&ehk=eXTi1xjwBS1%2bCbGCbG0hACaF1e398PQx1T2RB7AeZe0%3d&risl=&pid=ImgRaw&r=0",
         action: "deadlines"
      }
   ];

   if (activeTool === 'z-score') return <ZScoreView onBack={handleBack} />;
   if (activeTool === 'path-mapper') return <EducationPathMapperView onBack={handleBack} />;
   if (activeTool === 'career') return <CareerView onBack={handleBack} />;
   if (activeTool === 'compare') return <CompareView onBack={handleBack} />;
   if (activeTool === 'deadlines') return <DeadlinesView onBack={handleBack} />;

   return (
     
<div className="min-h-screen bg-slate-50 font-sans pb-20 transition-colors duration-300">
      {/* Hero Section */}
      <div className="relative h-[400px] bg-slate-900 overflow-hidden">
         {heroImages.map((img, index) => (
            <div 
               key={index}
               className={`absolute inset-0 transition-opacity duration-1000 ease-in-out ${
                  index === currentHeroIndex ? 'opacity-60' : 'opacity-0'
               }`}
            >
               <img src={img} className="w-full h-full object-cover" alt="Blog Hero" />
            </div>
         ))}
         <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/40 to-transparent"></div>
         <div className="absolute inset-0 flex flex-col justify-center items-center text-center px-4 animate-fade-in-up z-10">
            <span className="bg-blue-600 text-white px-4 py-1.5 rounded-full text-xs font-bold mb-6 uppercase tracking-widest shadow-lg">STRATEGIC PLANNING SUITE</span>
            <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight">Academic Hub.</h1>
            <p className="text-lg md:text-xl text-slate-300 max-w-2xl mx-auto">
                Data-driven modules designed to provide clarity and precision during your higher education journey.
            </p>
         </div>
      </div>
         <div className="container mx-auto px-6 -mt-24">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
               {tools.map((tool, i) => (
                  <div key={i} onClick={() => setSearchParams({ tool: tool.action })} className="bg-white dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 hover:border-primary-500 hover:shadow-premium transition-all duration-500 cursor-pointer group flex flex-col md:flex-row overflow-hidden reveal">
                     <div className="md:w-1/3 h-64 md:h-auto overflow-hidden relative">
                        <img src={tool.image} alt={tool.title} className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110" />
                        <div className="absolute inset-0 bg-gradient-to-t md:bg-gradient-to-r from-slate-950/60 to-transparent"></div>
                        {tool.badge && <span className="absolute top-6 left-6 bg-primary-600 text-white text-[9px] font-black px-4 py-2 rounded-xl uppercase tracking-widest">{tool.badge}</span>}
                     </div>
                     <div className="p-10 md:w-2/3 flex flex-col justify-center">
                        <h3 className="text-3xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">{tool.title}</h3>
                        <p className="text-slate-500 dark:text-slate-400 text-base mb-10 leading-relaxed font-medium">{tool.desc}</p>
                        <div className="flex items-center text-primary-600 font-black uppercase tracking-[0.2em] text-[10px] group-hover:translate-x-2 transition-all">
                           Open Module <ArrowRight size={18} className="ml-3" />
                        </div>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </div>
   );
};

const CareerView = ({ onBack }: { onBack: () => void }) => {
   const [interest, setInterest] = useState('');
   const [loading, setLoading] = useState(false);
   const [roadmap, setRoadmap] = useState<{ step: string, desc: string }[]>([]);

   const generateRoadmap = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!interest.trim()) return;
      setLoading(true);
      try {
         // const response = await ai.models.generateContent({
         //   model: 'gemini-3-flash-preview',
         //   contents: `Generate a 4-step academic and professional roadmap for someone interested in: ${interest}. Context: Sri Lanka.`,
         //   config: {
         //     responseMimeType: "application/json",
         //     responseSchema: {
         //       type: "ARRAY",
         //       items: {
         //         type: "OBJECT",
         //         properties: {
         //           step: { type: "STRING" },
         //           desc: { type: "STRING" }
         //         },
         //         required: ["step", "desc"]
         //       }
         //     }
         //   }
         // });
         // const data = JSON.parse(response.text || '[]');
         // setRoadmap(data);
      } catch (err) {
         console.error(err);
         setRoadmap([{ step: "Consultancy Error", desc: "Unable to reach AI advisor." }]);
      } finally {
         setLoading(false);
      }
   };

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-4xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="grid grid-cols-1 gap-12">
               <div className="bg-white dark:bg-slate-900 rounded-[3rem] p-12 border border-slate-100 dark:border-slate-800 shadow-premium reveal">
                  <div className="flex items-center gap-6 mb-12">
                     <div className="w-16 h-16 bg-primary-600 text-white rounded-[1.5rem] flex items-center justify-center shadow-premium"><Briefcase size={32} /></div>
                     <div>
                        <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight uppercase">AI Path Advisor</h2>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Intelligent Career Roadmap Generator</p>
                     </div>
                  </div>
                  <form onSubmit={generateRoadmap} className="space-y-10">
                     <div>
                        <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-4 ml-1">What are you passionate about?</label>
                        <textarea required value={interest} onChange={e => setInterest(e.target.value)} placeholder="e.g. Software engineering, marine biology, investment banking..." className="w-full bg-slate-50 dark:bg-slate-800 border-none rounded-2xl px-8 py-6 font-bold outline-none focus:ring-4 focus:ring-primary-500/10 transition-all h-32 resize-none text-slate-900 dark:text-white" />
                     </div>
                     <button type="submit" disabled={loading} className="w-full bg-primary-600 text-white font-bold uppercase tracking-[0.3em] text-[11px] py-6 rounded-2xl transition-all shadow-premium hover:bg-primary-700 active:scale-95 disabled:opacity-40">
                        {loading ? 'Consulting Gemini Intelligence...' : 'Generate Roadmap'}
                     </button>
                  </form>
               </div>

               {roadmap.length > 0 && (
                  <div className="space-y-6 animate-fade-in-up">
                     <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.4em] mb-8 text-center">Your Strategic Roadmap</h3>
                     {roadmap.map((item, i) => (
                        <div key={i} className="flex gap-8 group">
                           <div className="flex flex-col items-center">
                              <div className="w-10 h-10 bg-primary-600 text-white rounded-xl flex items-center justify-center font-bold text-sm shadow-premium z-10 shrink-0">{i + 1}</div>
                              {i < roadmap.length - 1 && <div className="w-0.5 h-full bg-slate-100 dark:bg-slate-800 my-2"></div>}
                           </div>
                           <div className="pb-12 pt-1">
                              <h4 className="text-xl font-black text-slate-900 dark:text-white mb-2 uppercase tracking-tight">{item.step}</h4>
                              <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed">{item.desc}</p>
                           </div>
                        </div>
                     ))}
                  </div>
               )}
            </div>
         </div>
      </div>
   );
};

// ... keep existing ZScoreView, CompareView, DeadlinesView implementations ...
const ZScoreView = ({ onBack }: { onBack: () => void }) => {
   const [stream, setStream] = useState('');
   const [district, setDistrict] = useState('');
   const [subjectSelections, setSubjectSelections] = useState<Array<{ key: string; subject: string; options?: string[]; grade: string }>>([]);
   const [loading, setLoading] = useState(false);
   const [result, setResult] = useState<any>(null);

   const streamsList = ['Physical Science', 'Biological Science', 'Commerce', 'Technology', 'Arts'];
   const districts = [
      'Ampara',
      'Anuradhapura',
      'Badulla',
      'Batticaloa',
      'Colombo',
      'Galle',
      'Gampaha',
      'Hambantota',
      'Jaffna',
      'Kalutara',
      'Kandy',
      'Kegalle',
      'Kilinochchi',
      'Kurunegala',
      'Mannar',
      'Matale',
      'Matara',
      'Monaragala',
      'Mullaitivu',
      'Nuwara Eliya',
      'Polonnaruwa',
      'Puttalam',
      'Ratnapura',
      'Trincomalee',
      'Vavuniya',
   ];

   const ARTS_MAJOR_SUBJECTS = [
      'Economics',
      'Geography',
      'History',
      'Home Economics',
      'Accounting',
      'Business Statistics',
      'Elements of Political Science',
      'Logic & Scientific Method',
      'Higher Mathematics',
      'Agricultural Science',
      'Mathematics',
      'Combined Mathematics',
      'Communication & Media Studies',
      'Information & Communication Technology',
   ];

   const ARTS_THIRD_SUBJECTS = [
      'Civil Technology',
      'Mechanical Technology',
      'Electronic and Information Technology',
      'Food Technology',
      'Agro Technology',
      'Bio-Resource Technology',
      'Buddhism',
      'Hinduism',
      'Christianity',
      'Islam',
      'Greek & Roman Civilization',
   ];

   const [physicalThirdSubject, setPhysicalThirdSubject] = useState<'Chemistry' | 'ICT'>('Chemistry');
   const [bioThirdSubject, setBioThirdSubject] = useState<'Physics' | 'Agriculture'>('Physics');
   const [commerceSecondSubject, setCommerceSecondSubject] = useState<'Business Studies' | 'ICT'>('Business Studies');
   const [commerceThirdSubject, setCommerceThirdSubject] = useState<'Economics' | 'Business Statistics' | 'ICT'>('Economics');
   const [techSecondSubject, setTechSecondSubject] = useState<'Bio System Technology' | 'Engineering Technology'>('Engineering Technology');
   const [techThirdSubject, setTechThirdSubject] = useState<'Agriculture' | 'Geography' | 'Business Studies' | 'ICT'>('ICT');

   const [artsFirstSubject, setArtsFirstSubject] = useState<string>(ARTS_MAJOR_SUBJECTS[0]);
   const [artsSecondSubject, setArtsSecondSubject] = useState<string>(ARTS_MAJOR_SUBJECTS[1]);
   const [artsThirdSubject, setArtsThirdSubject] = useState<string>(ARTS_THIRD_SUBJECTS[0]);

   useEffect(() => {
      if (!stream) {
         setSubjectSelections([]);
         return;
      }

      // Reset dependent subject defaults when stream changes (mirrors HomePage behavior)
      if (stream === 'Physical Science') setPhysicalThirdSubject('Chemistry');
      if (stream === 'Biological Science') setBioThirdSubject('Physics');
      if (stream === 'Commerce') {
         setCommerceSecondSubject('Business Studies');
         setCommerceThirdSubject('Economics');
      }
      if (stream === 'Technology') {
         setTechSecondSubject('Engineering Technology');
         setTechThirdSubject('ICT');
      }
      if (stream === 'Arts') {
         setArtsFirstSubject(ARTS_MAJOR_SUBJECTS[0]);
         setArtsSecondSubject(ARTS_MAJOR_SUBJECTS[1]);
         setArtsThirdSubject(ARTS_THIRD_SUBJECTS[0]);
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [stream]);

   useEffect(() => {
      if (!stream) {
         setSubjectSelections([]);
         return;
      }

      const artsSecondOptions = ARTS_MAJOR_SUBJECTS.filter((s) => s !== artsFirstSubject);

      const build = (rows: Array<{ key: string; subject: string; options?: string[] }>) => {
         setSubjectSelections((prev) => {
            const gradeByKey = new Map(prev.map((p) => [p.key, p.grade] as const));
            return rows.map((r) => ({
               key: r.key,
               subject: r.subject,
               options: r.options,
               grade: gradeByKey.get(r.key) ?? '',
            }));
         });
      };

      if (stream === 'Physical Science') {
         build([
            { key: 's1', subject: 'Combined Maths' },
            { key: 's2', subject: 'Physics' },
            { key: 's3', subject: physicalThirdSubject, options: ['Chemistry', 'ICT'] },
         ]);
         return;
      }

      if (stream === 'Biological Science') {
         build([
            { key: 's1', subject: 'Biology' },
            { key: 's2', subject: 'Chemistry' },
            { key: 's3', subject: bioThirdSubject, options: ['Physics', 'Agriculture'] },
         ]);
         return;
      }

      if (stream === 'Commerce') {
         build([
            { key: 's1', subject: 'Accounting' },
            { key: 's2', subject: commerceSecondSubject, options: ['Business Studies', 'ICT'] },
            { key: 's3', subject: commerceThirdSubject, options: ['Economics', 'Business Statistics', 'ICT'] },
         ]);
         return;
      }

      if (stream === 'Technology') {
         build([
            { key: 's1', subject: 'Science for Technology' },
            { key: 's2', subject: techSecondSubject, options: ['Bio System Technology', 'Engineering Technology'] },
            { key: 's3', subject: techThirdSubject, options: ['Agriculture', 'Geography', 'Business Studies', 'ICT'] },
         ]);
         return;
      }

      if (stream === 'Arts') {
         build([
            { key: 's1', subject: artsFirstSubject, options: ARTS_MAJOR_SUBJECTS },
            { key: 's2', subject: artsSecondSubject, options: artsSecondOptions.length > 0 ? artsSecondOptions : ARTS_MAJOR_SUBJECTS },
            { key: 's3', subject: artsThirdSubject, options: ARTS_THIRD_SUBJECTS },
         ]);
         return;
      }

      build([
         { key: 's1', subject: 'Subject 1' },
         { key: 's2', subject: 'Subject 2' },
         { key: 's3', subject: 'Subject 3' },
      ]);
   }, [stream, physicalThirdSubject, bioThirdSubject, commerceSecondSubject, commerceThirdSubject, techSecondSubject, techThirdSubject, artsFirstSubject, artsSecondSubject, artsThirdSubject]);

   const calculate = (e: any) => {
      e.preventDefault();
      setLoading(true);
      setTimeout(() => {
         setResult({ score: (Math.random() * 1.8 + 0.8).toFixed(4), status: "Admission Highly Likely" });
         setLoading(false);
      }, 1500);
   };

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-5xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
               <div className="bg-white dark:bg-slate-900 rounded-[3rem] p-12 border border-slate-100 dark:border-slate-800 shadow-premium reveal">
                  <div className="flex items-center gap-6 mb-12">
                     <div className="w-16 h-16 bg-primary-600 text-white rounded-[1.5rem] flex items-center justify-center shadow-premium"><Calculator size={32} /></div>
                     <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight uppercase">Z-Score Tool</h2>
                  </div>
                  <form onSubmit={calculate} className="space-y-8">
                     <div className="grid grid-cols-2 gap-4">
                        <select className="bg-slate-50 dark:bg-slate-800 rounded-xl px-6 py-4 font-bold outline-none" value={district} onChange={e => setDistrict(e.target.value)}>
                           <option value="">District</option>
                           {districts.map(d => <option key={d}>{d}</option>)}
                        </select>
                        <select className="bg-slate-50 dark:bg-slate-800 rounded-xl px-6 py-4 font-bold outline-none" value={stream} onChange={e => setStream(e.target.value)}>
                           <option value="">Stream</option>
                           {streamsList.map(s => <option key={s}>{s}</option>)}
                        </select>
                     </div>
                     {subjectSelections.map((s, i) => (
                        <div key={i} className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-800/30 rounded-2xl border border-slate-100 dark:border-slate-800">
                           {Array.isArray(s.options) && s.options.length > 0 ? (
                              <select
                                 className="bg-transparent border-none font-bold text-sm text-slate-800 dark:text-slate-200 outline-none"
                                 value={s.subject}
                                 onChange={(e) => {
                                    const next = e.target.value;
                                    if (stream === 'Physical Science' && s.key === 's3') setPhysicalThirdSubject(next as any);
                                    if (stream === 'Biological Science' && s.key === 's3') setBioThirdSubject(next as any);
                                    if (stream === 'Commerce' && s.key === 's2') setCommerceSecondSubject(next as any);
                                    if (stream === 'Commerce' && s.key === 's3') setCommerceThirdSubject(next as any);
                                    if (stream === 'Technology' && s.key === 's2') setTechSecondSubject(next as any);
                                    if (stream === 'Technology' && s.key === 's3') setTechThirdSubject(next as any);
                                    if (stream === 'Arts' && s.key === 's1') setArtsFirstSubject(next);
                                    if (stream === 'Arts' && s.key === 's2') setArtsSecondSubject(next);
                                    if (stream === 'Arts' && s.key === 's3') setArtsThirdSubject(next);
                                 }}
                              >
                                 {s.options.map((opt) => (
                                    <option key={opt} value={opt}>
                                       {opt}
                                    </option>
                                 ))}
                              </select>
                           ) : (
                              <span className="text-sm font-bold text-slate-800 dark:text-slate-200">{s.subject}</span>
                           )}

                           <select
                              className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl px-4 py-2 font-black text-xs"
                              value={s.grade}
                              onChange={(e) => {
                                 const nextGrade = e.target.value;
                                 setSubjectSelections((prev) => prev.map((row) => row.key === s.key ? { ...row, grade: nextGrade } : row));
                              }}
                           >
                              <option value="">Grade</option>
                              <option>A</option>
                              <option>B</option>
                              <option>C</option>
                              <option>S</option>
                              <option>F</option>
                           </select>
                        </div>
                     ))}
                     <button type="submit" disabled={!stream || loading} className="w-full bg-slate-900 dark:bg-primary-600 text-white font-bold uppercase tracking-[0.2em] text-[10px] py-6 rounded-2xl transition-all shadow-premium">
                        {loading ? 'Running UGC Model...' : 'Calculate Prediction'}
                     </button>
                  </form>
               </div>
               <div className="flex flex-col justify-center">
                  {result ? (
                     <div className="bg-slate-900 rounded-[3.5rem] p-16 text-center animate-fade-in-up">
                        <h3 className="text-[10px] font-bold text-slate-500 uppercase tracking-[0.4em] mb-6">Estimated Score</h3>
                        <div className="text-8xl font-black text-white mb-10 tracking-tighter">{result.score}</div>
                        <div className="inline-flex items-center gap-3 bg-emerald-500/10 text-emerald-500 text-[10px] font-bold uppercase tracking-[0.2em] px-8 py-4 rounded-2xl border border-emerald-500/20">
                           <ShieldCheck size={20} /> {result.status}
                        </div>
                     </div>
                  ) : (
                     <div className="h-full min-h-[400px] border-4 border-dashed border-slate-100 dark:border-slate-800 rounded-[3.5rem] flex flex-col items-center justify-center text-center p-12">
                        <Terminal size={48} className="text-slate-100 dark:text-slate-800 mb-6" />
                        <p className="text-slate-300 font-bold uppercase tracking-widest text-xs">Ready for Calculation</p>
                     </div>
                  )}
               </div>
            </div>
         </div>
      </div>
   );
};

const CompareView = ({ onBack }: { onBack: () => void }) => {
   const { compareCourses, toggleCompareCourse, clearCompareCourses } = useAppStore();
   const [loading, setLoading] = useState(false);
   const [loadError, setLoadError] = useState<string | null>(null);
   const [courseById, setCourseById] = useState<Record<string, any>>({});
   const [institutionById, setInstitutionById] = useState<Record<string, any>>({});

   type BotMessage = { id: string; role: 'bot' | 'user'; text: string; timestamp: number };
   const [botMessages, setBotMessages] = useState<BotMessage[]>([]);
   const [botInput, setBotInput] = useState('');
   const [botSeedKey, setBotSeedKey] = useState<string>('');

   const formatDuration = (d: any) => {
      if (!d || (typeof d === 'object' && !d.years && !d.months && !d.weeks)) return 'N/A';
      if (typeof d === 'string') return d;
      if (typeof d === 'object') {
         const parts: string[] = [];
         if (d.years) parts.push(`${d.years} Year${d.years > 1 ? 's' : ''}`);
         if (d.months) parts.push(`${d.months} Month${d.months > 1 ? 's' : ''}`);
         if (d.weeks) parts.push(`${d.weeks} Week${d.weeks > 1 ? 's' : ''}`);
         return parts.join(' ') || 'N/A';
      }
      return 'N/A';
   };

   const safeUrl = (website?: string) => {
      if (!website) return null;
      const trimmed = website.trim();
      if (!trimmed) return null;
      if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) return trimmed;
      return `https://${trimmed}`;
   };

   const formatFees = (fees: any): { text: string; numeric?: number } => {
      if (!fees) return { text: '—' };
      if (typeof fees === 'string') return { text: fees.trim() || '—' };
      if (typeof fees === 'number') return { text: fees.toLocaleString(), numeric: fees };
      if (typeof fees === 'object') {
         const amount = typeof fees.amount === 'number' ? fees.amount : undefined;
         const currency = typeof fees.currency === 'string' ? fees.currency : '';
         const label = amount != null ? `${currency ? currency + ' ' : ''}${amount.toLocaleString()}` : '';
         const breakdown = typeof fees.breakdown === 'string' ? fees.breakdown.trim() : '';
         if (label) return { text: label, numeric: amount };
         if (breakdown) return { text: breakdown };
      }
      return { text: '—' };
   };

   const getCourseTitle = (course: any) => String(course?.name || course?.title || '—');
   const getInstitutionName = (course: any) => {
      const instId = course?.institution_id;
      const inst = typeof instId === 'string' ? institutionById[instId] : null;
      return String(inst?.name || course?.institution_name || '—');
   };
   const getRequirements = (course: any) => {
      const req = course?.eligibility?.minimum_qualifications;
      return typeof req === 'string' && req.trim() ? req.trim() : '—';
   };
   const getDelivery = (course: any) => {
      const dm = course?.delivery_mode;
      if (Array.isArray(dm)) return dm.filter((v: any) => typeof v === 'string' && v.trim()).join(', ') || '—';
      if (typeof dm === 'string') return dm.trim() || '—';
      return '—';
   };

   const buildAutoComparisonText = (items: Array<{ id: string; course: any }>) => {
      if (!items.length) return 'Add 2–3 courses using the Compare button, then I’ll generate a comparison.';

      const lines: string[] = [];
      lines.push(`I loaded ${items.length} course${items.length > 1 ? 's' : ''} for comparison:`);
      lines.push('');

      const feeNumbers: Array<{ id: string; title: string; value: number }> = [];
      items.forEach(({ id, course }, idx) => {
         const title = getCourseTitle(course);
         const instName = getInstitutionName(course);
         const duration = formatDuration(course?.duration);
         const fees = formatFees(course?.fees);
         if (typeof fees.numeric === 'number') feeNumbers.push({ id, title, value: fees.numeric });
         const delivery = getDelivery(course);
         lines.push(`${idx + 1}) ${title}`);
         lines.push(`   Institution: ${instName}`);
         lines.push(`   Level: ${course?.level || '—'} | Duration: ${duration}`);
         lines.push(`   Delivery: ${delivery}`);
         lines.push(`   Investment: ${fees.text}`);
         lines.push(`   Requirements: ${getRequirements(course)}`);
         lines.push('');
      });

      if (feeNumbers.length >= 2) {
         const cheapest = feeNumbers.reduce((a, b) => (b.value < a.value ? b : a));
         lines.push(`Cheapest (based on numeric fee): ${cheapest.title}`);
      }

      lines.push('');
      lines.push('Ask me things like: “Which is cheapest?”, “Which is shortest duration?”, “Which has Online delivery?”, or “Summarize differences”.');
      return lines.join('\n');
   };

   const respondToQuestion = (questionRaw: string, items: Array<{ id: string; course: any }>) => {
      const q = questionRaw.toLowerCase();

      if (!items.length) return 'No courses selected yet. Add 2–3 courses using Compare first.';

      if (q.includes('cheapest') || q.includes('lowest') || q.includes('fee') || q.includes('cost')) {
         const withFees = items
            .map(({ course }) => ({ title: getCourseTitle(course), fees: formatFees(course?.fees) }))
            .filter((x) => typeof x.fees.numeric === 'number') as Array<{ title: string; fees: { text: string; numeric: number } }>;

         if (!withFees.length) return 'I can’t find numeric fee amounts for these courses. Fees are missing or not structured.';
         const cheapest = withFees.reduce((a, b) => (b.fees.numeric < a.fees.numeric ? b : a));
         return `Cheapest course is: ${cheapest.title} (${cheapest.fees.text}).`;
      }

      if (q.includes('shortest') || q.includes('duration') || q.includes('longest')) {
         // Simple: just list durations (normalizing to a readable string)
         const rows = items.map(({ course }) => `${getCourseTitle(course)} → ${formatDuration(course?.duration)}`);
         return `Durations:\n${rows.join('\n')}`;
      }

      if (q.includes('online')) {
         const online = items
            .filter(({ course }) => {
               const dm = course?.delivery_mode;
               return Array.isArray(dm)
                  ? dm.some((v: any) => typeof v === 'string' && v.toLowerCase().includes('online'))
                  : typeof dm === 'string'
                    ? dm.toLowerCase().includes('online')
                    : false;
            })
            .map(({ course }) => getCourseTitle(course));

         return online.length ? `Online available: ${online.join(', ')}` : 'None of the selected courses are marked as Online.';
      }

      if (q.includes('requirement') || q.includes('eligib') || q.includes('entry')) {
         const rows = items.map(({ course }) => `${getCourseTitle(course)} → ${getRequirements(course)}`);
         return `Requirements:\n${rows.join('\n')}`;
      }

      return buildAutoComparisonText(items);
   };

   useEffect(() => {
      let cancelled = false;

      const loadCourses = async () => {
         setLoadError(null);
         if (!compareCourses || compareCourses.length === 0) {
            setCourseById({});
            return;
         }

         setLoading(true);
         try {
            const results = await Promise.allSettled(compareCourses.map((id) => ProgramsService.getProgram(id)));
            if (cancelled) return;

            const next: Record<string, any> = {};
            results.forEach((r, idx) => {
               const id = compareCourses[idx];
               if (r.status === 'fulfilled') next[id] = r.value;
            });
            setCourseById(next);
         } catch (e: any) {
            if (cancelled) return;
            setLoadError(e?.message || 'Failed to load courses to compare.');
         } finally {
            if (!cancelled) setLoading(false);
         }
      };

      loadCourses();
      return () => {
         cancelled = true;
      };
   }, [compareCourses]);

   useEffect(() => {
      let cancelled = false;

      const loadInstitutions = async () => {
         const instIds = Array.from(
            new Set(
               compareCourses
                  .map((id) => courseById[id]?.institution_id)
                  .filter((v) => typeof v === 'string' && v.trim())
            )
         ) as string[];

         const missing = instIds.filter((id) => !institutionById[id]);
         if (missing.length === 0) return;

         const results = await Promise.allSettled(missing.map((id) => InstitutionsService.getInstitution(id)));
         if (cancelled) return;

         setInstitutionById((prev) => {
            const next = { ...prev };
            results.forEach((r, idx) => {
               const id = missing[idx];
               if (r.status === 'fulfilled') next[id] = r.value;
            });
            return next;
         });
      };

      loadInstitutions();
      return () => {
         cancelled = true;
      };
   }, [compareCourses, courseById, institutionById]);

   const comparedCourses = useMemo(() => {
      return compareCourses.map((id) => ({ id, course: courseById[id] })).filter(Boolean);
   }, [compareCourses, courseById]);

   // Auto-seed the bot whenever the selected compare set changes AND data is available.
   useEffect(() => {
      if (!compareCourses.length) {
         setBotMessages([]);
         setBotSeedKey('');
         return;
      }

      // Only seed once per unique loaded selection (prevents duplicate bot messages)
      const allLoaded = compareCourses.every((id) => Boolean(courseById[id]));
      if (!allLoaded) return;

      const key = compareCourses.join('|');
      if (key === botSeedKey) return;

      const items = compareCourses.map((id) => ({ id, course: courseById[id] }));
      const text = buildAutoComparisonText(items);
      setBotMessages([
         { id: 'bot-' + key, role: 'bot', text, timestamp: Date.now() },
      ]);
      setBotSeedKey(key);
   }, [compareCourses, courseById, institutionById, botSeedKey]);

   const metricRows: Array<{
      key: string;
      label: string;
      icon: React.ReactNode;
      render: (course: any) => React.ReactNode;
   }> = useMemo(() => {
      return [
         {
            key: 'name',
            label: 'Course',
            icon: <Briefcase size={16} className="text-primary-600" />,
            render: (course) => (
               <div className="text-xs font-black text-slate-900 dark:text-white uppercase leading-tight">
                  {course?.name || course?.title || '—'}
               </div>
            ),
         },
         {
            key: 'institution',
            label: 'Institution',
            icon: <Building2 size={16} className="text-primary-600" />,
            render: (course) => {
               const instId = course?.institution_id;
               const inst = typeof instId === 'string' ? institutionById[instId] : null;
               const instName = inst?.name || course?.institution_name || '—';
               return typeof instId === 'string' && instId ? (
                  <Link
                     to={`/institutions/${instId}`}
                     className="text-xs font-black text-primary-600 hover:text-primary-700 underline underline-offset-4"
                  >
                     {instName}
                  </Link>
               ) : (
                  <span className="text-xs font-bold text-slate-700 dark:text-slate-200">{instName}</span>
               );
            },
         },
         {
            key: 'level',
            label: 'Level',
            icon: <GraduationCap size={16} className="text-primary-600" />,
            render: (course) => <span className="text-xs font-bold text-slate-700 dark:text-slate-200">{course?.level || '—'}</span>,
         },
         {
            key: 'field',
            label: 'Field',
            icon: <BadgeCheck size={16} className="text-primary-600" />,
            render: (course) => <span className="text-xs font-bold text-slate-700 dark:text-slate-200">{course?.field || '—'}</span>,
         },
         {
            key: 'duration',
            label: 'Duration',
            icon: <Calendar size={16} className="text-primary-600" />,
            render: (course) => <span className="text-xs font-bold text-slate-700 dark:text-slate-200">{formatDuration(course?.duration)}</span>,
         },
         {
            key: 'fees',
            label: 'Investment',
            icon: <Banknote size={16} className="text-primary-600" />,
            render: (course) => {
               const fees = formatFees(course?.fees);
               return <span className="text-xs font-bold text-slate-700 dark:text-slate-200">{fees.text}</span>;
            },
         },
         {
            key: 'eligibility',
            label: 'Requirements',
            icon: <CheckCircle2 size={16} className="text-primary-600" />,
            render: (course) => {
               const req = course?.eligibility?.minimum_qualifications;
               const text = typeof req === 'string' && req.trim() ? req.trim() : '—';
               return <span className="text-[11px] font-bold text-slate-700 dark:text-slate-200 leading-snug">{text}</span>;
            },
         },
         {
            key: 'specializations',
            label: 'Specializations',
            icon: <Star size={16} className="text-primary-600" />,
            render: (course) => {
               const specs = Array.isArray(course?.specializations) ? course.specializations : [];
               const list = specs.filter((s: any) => typeof s === 'string' && s.trim()).map((s: string) => s.trim());
               const text = list.length ? list.slice(0, 8).join(', ') : '—';
               return <span className="text-[11px] font-bold text-slate-700 dark:text-slate-200 leading-snug">{text}</span>;
            },
         },
         {
            key: 'apply',
            label: 'Apply URL',
            icon: <Globe size={16} className="text-primary-600" />,
            render: (course) => {
               const raw = typeof course?.url === 'string' ? course.url : '';
               const url = raw ? safeUrl(raw) : null;
               if (!url) return <span className="text-slate-300">—</span>;
               return (
                  <a
                     href={url}
                     target="_blank"
                     rel="noreferrer"
                     className="text-xs font-black text-primary-600 hover:text-primary-700 underline underline-offset-4"
                  >
                     Open
                  </a>
               );
            },
         },
      ];
   }, [institutionById]);

   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-7xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Matrix</button>

            {compareCourses.length === 0 ? (
               <div className="h-full border-4 border-dashed border-slate-100 dark:border-slate-800 rounded-[3rem] flex flex-col items-center justify-center p-20 text-center">
                  <ShieldCheck size={48} className="mb-6 text-slate-100 dark:text-slate-800" />
                  <h3 className="text-xl font-bold uppercase tracking-tight text-slate-300">No courses selected</h3>
                  <p className="text-slate-400 font-medium mt-3">Open a course and click “Compare”. You can add up to 3.</p>
                  <Link to="/courses" className="mt-6 inline-flex items-center gap-2 bg-primary-600 text-white px-6 py-3 rounded-2xl font-black uppercase tracking-widest text-[10px] shadow-premium">
                     Browse Courses <ArrowRight size={16} />
                  </Link>
               </div>
            ) : (
               <div className="space-y-8">
                  <div className="bg-white dark:bg-slate-900 rounded-[3rem] border border-slate-100 dark:border-slate-800 shadow-premium p-10">
                     <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
                        <div>
                           <h2 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight uppercase">Course Comparison</h2>
                           <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-2">Up to 3 courses side-by-side</p>
                        </div>
                        <div className="flex items-center gap-3">
                           <button
                              onClick={clearCompareCourses}
                              className="px-5 py-3 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-[10px] font-black uppercase tracking-widest text-slate-500 hover:text-primary-600"
                           >
                              Clear All
                           </button>
                        </div>
                     </div>

                     {loadError && (
                        <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-[11px] font-bold text-amber-800">
                           {loadError}
                        </div>
                     )}

                     {loading && (
                        <div className="mt-6 rounded-2xl border border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 px-4 py-3 text-[11px] font-bold text-slate-500">
                           Loading courses...
                        </div>
                     )}

                     <div className="mt-6 flex flex-wrap gap-3">
                        {comparedCourses.map(({ id, course }) => {
                           const name = course?.name || course?.title || id;
                           return (
                              <div key={id} className="flex items-center gap-3 rounded-2xl border border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 px-4 py-3">
                                 <div className="min-w-0">
                                    <div className="font-black text-xs text-slate-900 dark:text-white truncate max-w-[260px]">{name}</div>
                                    <div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{course?.level || '—'}</div>
                                 </div>
                                 <div className="flex items-center gap-2">
                                    <Link
                                       to={`/courses/${id}`}
                                       className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-[10px] font-black uppercase tracking-widest text-primary-600"
                                    >
                                       View
                                    </Link>
                                    <button
                                       onClick={() => toggleCompareCourse(id)}
                                       className="p-2 rounded-xl hover:bg-white dark:hover:bg-slate-900 transition-colors"
                                       aria-label={`Remove ${name}`}
                                    >
                                       <X size={16} className="text-slate-400 hover:text-primary-600" />
                                    </button>
                                 </div>
                              </div>
                           );
                        })}
                     </div>
                  </div>

                  <div className="bg-white dark:bg-slate-900 rounded-[3rem] border border-slate-100 dark:border-slate-800 overflow-hidden shadow-premium">
                     <div className="overflow-x-auto">
                        <div
                           className="grid divide-x divide-slate-100 dark:divide-slate-800"
                           style={{ gridTemplateColumns: `240px repeat(${compareCourses.length}, minmax(220px, 1fr))` }}
                        >
                           <div className="p-8 bg-slate-50 dark:bg-slate-950 font-black text-[9px] text-slate-400 uppercase tracking-widest flex items-center">
                              Course Metrics
                           </div>
                           {compareCourses.map((id) => {
                              const course = courseById[id];
                              const name = course?.name || course?.title || '—';
                              return (
                                 <div key={id} className="p-8 text-center bg-slate-50 dark:bg-slate-950">
                                    <div className="font-black text-xs text-slate-900 dark:text-white uppercase leading-tight">{name}</div>
                                    <div className="text-[10px] font-black uppercase tracking-widest text-slate-400 mt-2">{course?.level || ''}</div>
                                 </div>
                              );
                           })}

                           {metricRows.map((row) => (
                              <React.Fragment key={row.key}>
                                 <div className="p-8 text-[10px] font-black text-slate-500 dark:text-slate-400 uppercase tracking-widest border-t border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 flex items-center gap-3">
                                    {row.icon}
                                    {row.label}
                                 </div>
                                 {compareCourses.map((id) => (
                                    <div
                                       key={`${row.key}-${id}`}
                                       className="p-8 text-center border-t border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900"
                                    >
                                       {row.render(courseById[id])}
                                    </div>
                                 ))}
                              </React.Fragment>
                           ))}
                        </div>
                     </div>
                  </div>

                  {/* Embedded comparison bot */}
                  <div className="bg-white dark:bg-slate-900 rounded-[3rem] border border-slate-100 dark:border-slate-800 shadow-premium overflow-hidden">
                     <div className="p-10 border-b border-slate-100 dark:border-slate-800">
                        <div className="flex items-center justify-between gap-6">
                           <div>
                              <h3 className="text-xl font-black text-slate-900 dark:text-white uppercase tracking-tight">Comparison Bot</h3>
                              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-2">Auto summary based on selected courses</p>
                           </div>
                           <button
                              onClick={() => setBotMessages([])}
                              className="px-5 py-3 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 text-[10px] font-black uppercase tracking-widest text-slate-500 hover:text-primary-600"
                           >
                              Clear Chat
                           </button>
                        </div>
                     </div>

                     <div className="p-10">
                        <div className="h-[280px] overflow-y-auto rounded-3xl border border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 p-6 space-y-4">
                           {botMessages.length === 0 ? (
                              <div className="text-slate-500 text-sm font-medium">
                                 Select 2–3 courses and I’ll generate a comparison.
                              </div>
                           ) : (
                              botMessages.map((m) => (
                                 <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                    <div className={`${m.role === 'user' ? 'bg-primary-600 text-white' : 'bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100'} max-w-[85%] rounded-3xl px-5 py-4 text-sm leading-relaxed border border-slate-100 dark:border-slate-800 whitespace-pre-wrap`}>
                                       {m.text}
                                    </div>
                                 </div>
                              ))
                           )}
                        </div>

                        <form
                           onSubmit={(e) => {
                              e.preventDefault();
                              const text = botInput.trim();
                              if (!text) return;
                              const items = compareCourses.map((id) => ({ id, course: courseById[id] })).filter((x) => x.course);

                              const userMsg: BotMessage = { id: 'user-' + Date.now(), role: 'user', text, timestamp: Date.now() };
                              const botReply = respondToQuestion(text, items);
                              const botMsg: BotMessage = { id: 'bot-' + Date.now(), role: 'bot', text: botReply, timestamp: Date.now() };

                              setBotMessages((prev) => [...prev, userMsg, botMsg]);
                              setBotInput('');
                           }}
                           className="mt-6 flex gap-3"
                        >
                           <input
                              value={botInput}
                              onChange={(e) => setBotInput(e.target.value)}
                              placeholder="Ask: cheapest? shortest? online? requirements?"
                              className="flex-1 bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-2xl px-5 py-4 text-sm font-bold outline-none focus:ring-4 focus:ring-primary-500/10"
                           />
                           <button
                              type="submit"
                              className="px-6 py-4 rounded-2xl bg-primary-600 hover:bg-primary-700 text-white text-[10px] font-black uppercase tracking-widest shadow-premium"
                           >
                              Send
                           </button>
                        </form>
                     </div>
                  </div>
               </div>
            )}
         </div>
      </div>
   );
};

const DeadlinesView = ({ onBack }: { onBack: () => void }) => {
   return (
      <div className="min-h-screen bg-[#fcfdfe] dark:bg-slate-950 py-24 px-6">
         <div className="max-w-4xl mx-auto">
            <button onClick={onBack} className="flex items-center text-[10px] font-bold uppercase tracking-[0.3em] text-slate-400 hover:text-primary-600 mb-12 transition-colors"><ArrowLeft size={18} className="mr-4" /> Exit Module</button>
            <div className="flex items-center gap-6 mb-16 animate-fade-in-up">
               <div className="w-16 h-16 bg-primary-600 text-white rounded-2xl flex items-center justify-center shadow-premium"><Calendar size={32} /></div>
               <div>
                  <h1 className="text-4xl font-black text-slate-900 dark:text-white uppercase tracking-tight">Intake Sync</h1>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Application Cycle Tracker</p>
               </div>
            </div>
            <div className="space-y-4">
               {[
                  { title: "UGC State University Intake", date: "Oct 15, 2024", tag: "Government", urgent: true },
                  { title: "SLIIT Semester One Admissions", date: "Sep 30, 2024", tag: "Private", urgent: true },
                  { title: "VTA Vocational Enrollment", date: "Dec 12, 2024", tag: "Vocational", urgent: false }
               ].map((item, i) => (
                  <div key={i} className="bg-white dark:bg-slate-900 p-10 rounded-4xl border border-slate-100 dark:border-slate-800 flex justify-between items-center group hover:shadow-premium transition-all">
                     <div>
                        <span className="text-[9px] font-bold text-primary-600 uppercase tracking-widest bg-primary-50 px-4 py-1.5 rounded-lg mb-4 inline-block">{item.tag}</span>
                        <h3 className="font-black text-2xl text-slate-900 dark:text-white group-hover:text-primary-600 transition-colors">{item.title}</h3>
                     </div>
                     <div className="text-right">
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-1">Final Deadline</p>
                        <p className={`text-xl font-black ${item.urgent ? 'text-red-500' : 'text-slate-900 dark:text-white'}`}>{item.date}</p>
                     </div>
                  </div>
               ))}
            </div>
         </div>
      </div>
   );
};

const ForumView = ({ onBack }: { onBack: () => void }) => null; // Placeholder for logic balance

export default Tools;